a= input("请输入姓名是：")
b= input("请输入年龄是：")
weight = input("你的体重是：")
haight = input("你的身高是：")
beautiful = input("你的球龄是：")
print("姓名:%s"%a)
print("年龄:%s"%b)
print("体重:%s克"%weight)
print("身高:%s厘米"%haight)
print("球龄:%s"%beautiful)
